version: '3.8'

services:
  # Bitcoin Core node (regtest)
  bitcoind:
    image: bitcoin/bitcoin-core:25.0
    container_name: runes-lightning-bitcoind
    command: >
      bitcoind
      -regtest
      -server=1
      -rpcuser=bitcoin
      -rpcpassword=bitcoin
      -rpcallowip=0.0.0.0/0
      -rpcbind=0.0.0.0
      -txindex=1
      -blockfilterindex=1
      -peerbloomfilters=1
      -acceptnonstdtxn=0
      -datadir=/bitcoin
    ports:
      - "18443:18443"  # RPC
      - "18444:18444"  # P2P
    volumes:
      - bitcoin_data:/bitcoin
    networks:
      - runes-lightning-network
    restart: unless-stopped

  # LND node (for Go integration)
  lnd:
    image: lightninglabs/lnd:latest
    container_name: runes-lightning-lnd
    command: >
      lnd
      --network=regtest
      --bitcoin.active=1
      --bitcoin.regtest=1
      --bitcoin.node=bitcoind
      --bitcoind.rpcuser=bitcoin
      --bitcoind.rpcpass=bitcoin
      --bitcoind.rpchost=bitcoind
      --bitcoind.rpcport=18443
      --bitcoind.zmqpubrawblock=tcp://bitcoind:28332
      --bitcoind.zmqpubrawtx=tcp://bitcoind:28333
      --rpclisten=0.0.0.0:10009
      --restlisten=0.0.0.0:8080
      --listen=0.0.0.0:9735
      --debuglevel=debug
    ports:
      - "10009:10009"  # gRPC
      - "8080:8080"    # REST API
      - "9735:9735"    # Lightning P2P
    volumes:
      - lnd_data:/root/.lnd
    depends_on:
      - bitcoind
    networks:
      - runes-lightning-network
    restart: unless-stopped

  # Ordinals indexer (for Rust integration)
  ord-indexer:
    image: ghcr.io/casey/ord:latest
    container_name: runes-lightning-ord
    command: >
      ord
      --bitcoin-rpc-url=http://bitcoin:bitcoin@bitcoind:18443
      --data-dir=/ord-data
      server
      --http-port=8081
      --http-addr=0.0.0.0:8081
    ports:
      - "8081:8081"  # Ordinals API
    volumes:
      - ord_data:/ord-data
    depends_on:
      - bitcoind
    networks:
      - runes-lightning-network
    restart: unless-stopped

volumes:
  bitcoin_data:
    driver: local
  lnd_data:
    driver: local
  ord_data:
    driver: local

networks:
  runes-lightning-network:
    driver: bridge 